### ISSUE TITLE
corrupted headline icons when in active state

### ISSUE THREAD

**Issue by githubertus** [sathish4fri/ossnfacebook#1]
![facebook-headline-icons](https://cloud.githubusercontent.com/assets/9904364/5488552/c4cc0a10-86bf-11e4-85cf-c3ffab72b722.png)

.................................
latest release / browser independant

No wonder, when using a 1:1 copy of the original style
.ossn-icons-topbar-friends-new{
    background-position: 0 -76px ;
    width: 22px;
    height: 19px;
}
in combination with a topbar.png that's totally different.

**Comment by sathish4fri** [comment]
yes your right .. let me add the changes now

**Comment by githubertus** [comment]
friends notification still not working !
because you mistakenly deleted the DOT in the beginning of line
->->   ossn-icons-topbar-friends-new 
:)
